name: Deploy to Amazon EC2
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 6uiwj/myselectshop
  VERSION: latest

jobs:
  Deploy:
    name: Build Docker Image and Deploy EC2
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    environment: deploy
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK # JDK 지정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21 #자바 버전은 본인에 맞게
          cache: gradle
      - name: Build container image # 도커 이미지 생성
        run: |
          chmod +x gradlew
          ./gradlew bootJar
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
      - name: Log into container registry # 깃허브 이미지 컨테이너 로그인 및 push
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ koreait.xyz }}
          username: ${{ jmj }}
          key: ${{ _aA123456 }}
          port: ${{ 22 }}
          script: | 
            sh deploy.sh